name: PR convention

on:
    pull_request:
        types: [opened, edited, synchronize, reopened]

jobs:
    validate_pr:
        runs-on: ubuntu-latest
        steps:
            - name: Enforce PR naming convention
              uses: deepakputhraya/action-pr-title@v1.0.2
              with:
                  regex: '^\[(HLSP|HLS)-\d{1,5}\].*|^\[renovate\].*|^Bump .* from .* to .* in .*'
