name: Release

on:
    workflow_dispatch:
      inputs:
        proxy_lib:
          type: choice
          description: 'Proxy lib name'
          options:
            - github.com/helios/go-sdk/proxy-libs/helioshttp
            - github.com/helios/go-sdk/proxy-libs/heliosgrpc
            - github.com/helios/go-sdk/proxy-libs/heliosmongo
            - github.com/helios/go-sdk/proxy-libs/heliosgin
            - github.com/helios/go-sdk/proxy-libs/heliosmux
            - github.com/helios/go-sdk/proxy-libs/heliosecho
            - github.com/helios/go-sdk/proxy-libs/helioschi
            - github.com/helios/go-sdk/proxy-libs/heliosmacaron
            - github.com/helios/go-sdk/proxy-libs/heliossarama
            - github.com/helios/go-sdk/proxy-libs/helioslambda
            - github.com/helios/go-sdk/proxy-libs/helioss3
            - github.com/helios/go-sdk/proxy-libs/heliosdynamodb
            - github.com/helios/go-sdk/proxy-libs/heliossqs
            - github.com/helios/go-sdk/proxy-libs/helioseventbridge
          required: true
        proxy_lib_version:
          description: 'Proxy lib version'
          required: true  
        min_version_supported:
          description: 'Original package last supported version'
          required: true    

jobs:
    test:
        uses: ./.github/workflows/test.yml
        secrets:
          ACTIONS_GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
    tag:
        runs-on: ubuntu-latest
        needs: [test]
        env:
          GH_ACCESS_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Tag and push
            run: |
              git tag proxy-libs/${{ github.event.inputs.proxy_lib }}/${{ github.event.inputs.proxy_lib_version }} && git push origin proxy-libs/${{ github.event.inputs.proxy_lib }}/${{ github.event.inputs.proxy_lib_version }}
          
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-1

          - name: Get current proxy_libs_version.json
            run: |
              aws s3 cp https://d1wp6iv35l684a.cloudfront.net/proxy_libs_versions.json ./proxy-libs

          - name: Set up Python 3.7          
            uses: actions/setup-python@v2
            with:
              python-version: '3.7'

          - name: Update proxy-libs version json
            working-directory: proxy-libs
            run: |
              python3 version_helper.py ${{ github.event.inputs.proxy_lib }} ${{ github.event.inputs.proxy_lib_version }} ${{ github.event.inputs.min_version_supported }}
          
          - name: Upload updated proxy_libs_version.json to s3
            run: |
              aws s3 cp ./proxy-libs/proxy_libs_versions.json s3://www.heliosphere.io/proxy_libs_versions.json