name: Test

on:
    push:
        branches: [main]

    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            go: [ "1.18", "1.19" ]
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Setup Go
            uses: actions/setup-go@v3
            with:
                go-version: ${{ matrix.go }}

          - name: Setup Go Environment
            run: |
              echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
              echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

          - name: Cache Go
            id: module-cache
            uses: actions/cache@v2
            with:
              path: |
                /home/runner/go/pkg/mod
              key: v1-go-pkg-mod-${{ runner.os }}-${{ hashFiles('**/go.mod', '**/go.sum') }}

          - name: Install dependencies
            working-directory: sdk
            if: steps.module-cache.outputs.hit != 'true'
            run: go mod download && go mod verify

          - name: Run sdk unit tests
            working-directory: sdk
            run: go test

          - name: Run http proxy unit tests
            working-directory: proxy-libs/helioshttp
            run: go mod tidy && go test .

          - name: Run grpc proxy unit tests
            working-directory: proxy-libs/heliosgrpc
            run: go mod tidy && go test .
